package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CiAddress generated by hbm2java
 */
public class CiAddress implements java.io.Serializable {
    
    
     private BigDecimal id;
     private String administrativearea;
     private String city;
     private String country;
     private String postalcode;
     private BigDecimal ci_contactid;

    public CiAddress() {
    }

	
    public CiAddress(BigDecimal id) {
        this.id = id;
    }
    public CiAddress(BigDecimal id, String administrativearea, String city, String country, String postalcode, BigDecimal ci_contactid) {
       this.id = id;
       this.administrativearea = administrativearea;
       this.city = city;
       this.country = country;
       this.postalcode = postalcode;
       this.ci_contactid = ci_contactid;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getAdministrativearea() {
        return this.administrativearea;
    }
    
    public void setAdministrativearea(String administrativearea) {
        this.administrativearea = administrativearea;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }
    public BigDecimal getCi_contactid() {
        return this.ci_contactid;
    }
    
    public void setCi_contactid(BigDecimal ci_contactid) {
        this.ci_contactid = ci_contactid;
    }




}


