package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CiAddressDeliveryPoint generated by hbm2java
 */
public class CiCitationAlternateTitle implements java.io.Serializable {


    private BigDecimal ci_citationid;
    private String alternateTitle;

    public CiCitationAlternateTitle() {
        
    }
	
    public CiCitationAlternateTitle(BigDecimal ci_citationid) {
        this.ci_citationid = ci_citationid;
    }
    public CiCitationAlternateTitle(BigDecimal ci_citationid, String alternateTitle) {
       this.ci_citationid = ci_citationid;
       this.alternateTitle = alternateTitle;
    }

    public BigDecimal getCi_citationid() {
        return ci_citationid;
    }

    public void setCi_citationid(BigDecimal ci_citationid) {
        this.ci_citationid = ci_citationid;
    }

    public String getAlternateTitle() {
        return alternateTitle;
    }

    public void setAlternateTitle(String alternateTitle) {
        this.alternateTitle = alternateTitle;
    }

}


