package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CiCitation generated by hbm2java
 */
public class CiCitation implements java.io.Serializable {


     private BigDecimal id;
     private String collectiveTitle;
     private String edition;
     private Date editionDate;
     private String isbn;
     private String issn;
     private String otherCitationDetails;
     private String title;
     private BigDecimal mdAggregateInfoId;
     private BigDecimal mdApplicationschemaInfoId;
     private BigDecimal dqConformanceResultId;
     private BigDecimal dqElementId;
     private BigDecimal mdFeatureCatalogueDescId;
     private BigDecimal mdGeoReferenceAbleId;
     private BigDecimal mdIdentificationId;
     private BigDecimal mdKeywordId;
     private BigDecimal mdIdentifierId;
     private BigDecimal mdPortrayalCatalogueRefId;
     private BigDecimal liSourceId;
     private BigDecimal svServiceIdentificationId;
     private BigDecimal rsIdentifierId;

    public CiCitation() {
    }

    public BigDecimal getId() {
        return id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getCollectiveTitle() {
        return collectiveTitle;
    }

    public void setCollectiveTitle(String collectiveTitle) {
        this.collectiveTitle = collectiveTitle;
    }

    public String getEdition() {
        return edition;
    }

    public void setEdition(String edition) {
        this.edition = edition;
    }

    public Date getEditionDate() {
        return editionDate;
    }

    public void setEditionDate(Date editionDate) {
        this.editionDate = editionDate;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getIssn() {
        return issn;
    }

    public void setIssn(String issn) {
        this.issn = issn;
    }

    public String getOtherCitationDetails() {
        return otherCitationDetails;
    }

    public void setOtherCitationDetails(String otherCitationDetails) {
        this.otherCitationDetails = otherCitationDetails;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public BigDecimal getMdAggregateInfoId() {
        return mdAggregateInfoId;
    }

    public void setMdAggregateInfoId(BigDecimal mdAggregateInfoId) {
        this.mdAggregateInfoId = mdAggregateInfoId;
    }

    public BigDecimal getMdApplicationschemaInfoId() {
        return mdApplicationschemaInfoId;
    }

    public void setMdApplicationschemaInfoId(BigDecimal mdApplicationschemaInfoId) {
        this.mdApplicationschemaInfoId = mdApplicationschemaInfoId;
    }

    public BigDecimal getDqConformanceResultId() {
        return dqConformanceResultId;
    }

    public void setDqConformanceResultId(BigDecimal dqConformanceResultId) {
        this.dqConformanceResultId = dqConformanceResultId;
    }

    public BigDecimal getDqElementId() {
        return dqElementId;
    }

    public void setDqElementId(BigDecimal dqElementId) {
        this.dqElementId = dqElementId;
    }

    public BigDecimal getMdFeatureCatalogueDescId() {
        return mdFeatureCatalogueDescId;
    }

    public void setMdFeatureCatalogueDescId(BigDecimal mdFeatureCatalogueDescId) {
        this.mdFeatureCatalogueDescId = mdFeatureCatalogueDescId;
    }

    public BigDecimal getMdGeoReferenceAbleId() {
        return mdGeoReferenceAbleId;
    }

    public void setMdGeoReferenceAbleId(BigDecimal mdGeoReferenceAbleId) {
        this.mdGeoReferenceAbleId = mdGeoReferenceAbleId;
    }

    public BigDecimal getMdIdentificationId() {
        return mdIdentificationId;
    }

    public void setMdIdentificationId(BigDecimal mdIdentificationId) {
        this.mdIdentificationId = mdIdentificationId;
    }

    public BigDecimal getMdKeywordId() {
        return mdKeywordId;
    }

    public void setMdKeywordId(BigDecimal mdKeywordId) {
        this.mdKeywordId = mdKeywordId;
    }

    public BigDecimal getMdIdentifierId() {
        return mdIdentifierId;
    }

    public void setMdIdentifierId(BigDecimal mdIdentifierId) {
        this.mdIdentifierId = mdIdentifierId;
    }

    public BigDecimal getMdPortrayalCatalogueRefId() {
        return mdPortrayalCatalogueRefId;
    }

    public void setMdPortrayalCatalogueRefId(BigDecimal mdPortrayalCatalogueRefId) {
        this.mdPortrayalCatalogueRefId = mdPortrayalCatalogueRefId;
    }

    public BigDecimal getLiSourceId() {
        return liSourceId;
    }

    public void setLiSourceId(BigDecimal liSourceId) {
        this.liSourceId = liSourceId;
    }

    public BigDecimal getSvServiceIdentificationId() {
        return svServiceIdentificationId;
    }

    public void setSvServiceIdentificationId(BigDecimal svServiceIdentificationId) {
        this.svServiceIdentificationId = svServiceIdentificationId;
    }

    public BigDecimal getRsIdentifierId() {
        return rsIdentifierId;
    }

    public void setRsIdentifierId(BigDecimal rsIdentifierId) {
        this.rsIdentifierId = rsIdentifierId;
    }

	
    


}


