package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MdMetadataHierarchylvName generated by hbm2java
 */
public class MdMetadataHierarchylvName implements java.io.Serializable {


     private BigDecimal mdMetadataid;
     private String hierarchylevelName;

    public MdMetadataHierarchylvName() {
    }
	
    public MdMetadataHierarchylvName(BigDecimal mdMetadataid) {
        this.mdMetadataid = mdMetadataid;
    }
    public MdMetadataHierarchylvName(BigDecimal mdMetadataid, String hierarchylevelName) {
       this.mdMetadataid = mdMetadataid;
       this.hierarchylevelName = hierarchylevelName;
    }
   
    public BigDecimal getMdMetadataid() {
        return this.mdMetadataid;
    }
    
    public void setMdMetadataid(BigDecimal mdMetadataid) {
        this.mdMetadataid = mdMetadataid;
    }
    public String getHierarchylevelName() {
        return this.hierarchylevelName;
    }
    
    public void setHierarchylevelName(String hierarchylevelName) {
        this.hierarchylevelName = hierarchylevelName;
    }




}


