package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CiAddressDeliveryPoint generated by hbm2java
 */
public class CiAddressDeliveryPoint implements java.io.Serializable {


     private BigDecimal ci_addressid;
     private String deliverypoint;

    public CiAddressDeliveryPoint() {
    }

	
    public CiAddressDeliveryPoint(BigDecimal ci_addressid) {
        this.ci_addressid = ci_addressid;
    }
    public CiAddressDeliveryPoint(BigDecimal ci_addressid, String deliverypoint) {
       this.ci_addressid = ci_addressid;
       this.deliverypoint = deliverypoint;
    }
   
    public BigDecimal getCi_addressid() {
        return this.ci_addressid;
    }
    
    public void setCi_addressid(BigDecimal ci_addressid) {
        this.ci_addressid = ci_addressid;
    }
    public String getDeliverypoint() {
        return this.deliverypoint;
    }
    
    public void setDeliverypoint(String deliverypoint) {
        this.deliverypoint = deliverypoint;
    }




}


