/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.DataConfiguration;
import config.HibernateUtil;
import config.HibernateUtilXml;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.hibernate.SessionFactory;
import test.Test;
import test.testMain;

/**
 *
 * @author wallet
 */
public class KoneksiView extends javax.swing.JFrame {

    /**
     * Creates new form koneksiView
     */
    private MigrasiMetadata metadata = null;

    public KoneksiView() {
        initComponents();
        setUserInterface();
//        setVariableToEmpty();
             loader.setText("");
        //loader.setVisible(false);
    }

    public void setVariableToEmpty() {
        txt_ip.setText("");
        txt_password.setText("");
        txt_port.setText("");
        txt_dbname.setText("");
        txt_username.setText("");
//        loader.setText("");
//        loader.setVisible(false);
    }

    public void setUserInterface() {
        this.setTitle("Koneksi Metadata");
        setLocationRelativeTo(this);
    }

    private ArrayList<DataConfiguration> listData = new ArrayList<>();

    private static final Pattern PATTERN = Pattern.compile(
            "^(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])$");

    public static boolean validate(final String ip) {
        return PATTERN.matcher(ip).matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPilihBerkas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ip = new javax.swing.JTextField();
        button_hapus = new javax.swing.JButton();
        button_simpan = new javax.swing.JButton();
        button_batal = new javax.swing.JButton();
        txt_dbname = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        loader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("IP");

        jLabel5.setText("DB NAME ");

        jLabel6.setText("PORT");

        jLabel7.setText("PASSWORD DB");

        txt_ip.setText("virtua.co.id");

        button_hapus.setText("Hapus");
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });

        button_simpan.setText("Simpan");
        button_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpanActionPerformed(evt);
            }
        });

        button_batal.setText("Batal");
        button_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_batalActionPerformed(evt);
            }
        });

        txt_dbname.setText("igsver2");
        txt_dbname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dbnameActionPerformed(evt);
            }
        });

        txt_port.setText("1522");
        txt_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_portActionPerformed(evt);
            }
        });

        txt_password.setText("Virtua2017");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel8.setText("USERNAME DB");

        txt_username.setText("system");

        loader.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loader.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dbname, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txt_port, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txt_password)
                            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loader))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dbname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(loader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        // TODO add your handling code here:
        txt_ip.setText("");
        txt_password.setText("");
        txt_port.setText("");
        txt_dbname.setText("");
        //txt_ip.setFocusable(true);
    }//GEN-LAST:event_button_hapusActionPerformed

    private void button_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpanActionPerformed
        // TODO add your handling code here:
        DataConfiguration dataConfiguration = new DataConfiguration();
        
        String ipAddress = txt_ip.getText();
        String port = txt_port.getText();
        String userName = txt_username.getText();
        String password = txt_password.getText();
        String dbname = txt_dbname.getText();
       
        boolean isIpValied = validate(ipAddress);
        boolean isIpEmpty = ipAddress.isEmpty();
        boolean isPortEmpty = (port.isEmpty() || port.equals(""));
        boolean isUsernameEmpty = (userName.isEmpty() || userName.equals(""));
        boolean isPasswordEmpty = (password.isEmpty() || password.equals(""));

//        if (!isIpValied) {
//            JOptionPane.showMessageDialog(rootPane, "alamat ip tidak valid");
//            return;
//        }
        if (isIpEmpty) {
            JOptionPane.showMessageDialog(rootPane, "alamat ip tidak boleh kosong");
            return;
        }
        if (isPortEmpty) {
            JOptionPane.showMessageDialog(rootPane, "Nama database tidak boleh kosong");
            return;
        }
        if (isUsernameEmpty) {
            JOptionPane.showMessageDialog(rootPane, "Username tidak boleh kosong");
            return;
        }
        if (isPasswordEmpty) {
            JOptionPane.showMessageDialog(rootPane, "Password tidak boleh kosong");
            return;
        }

        dataConfiguration.setIp(ipAddress);
        dataConfiguration.setDatabaseName(dbname);
        dataConfiguration.setPort(port);
        dataConfiguration.setUsername(userName);
        dataConfiguration.setPassword(password);
        
        loader.setText("connecting ...");
        
        Thread thread = new Thread(){
            
           public void run(){

                try{
                      
                        HibernateUtilXml hibernateUtilXml = new HibernateUtilXml(dataConfiguration);
                        SessionFactory sessionFactory = hibernateUtilXml.buildSession();
                        
                        if(sessionFactory.isOpen()){
                            
                            MigrasiMetadata metadata = new MigrasiMetadata(hibernateUtilXml);
                            dispose();
                            metadata.setVisible(true);
                            
                             
                            if(metadata.isDisplayable()){
                                //System.out.println("yrd");
                                 metadata.setVisible(true);
                            }else{
                                // System.out.println("yrddd");
                                 metadata.setVisible(false);
                            }
//                           
                        }
                        
                }catch(NullPointerException n){
                      
                   n.printStackTrace();
                   
                   JOptionPane.showMessageDialog(rootPane, "gagal menghubungkan, periksa ulang koneksi");
                   loader.setText("");
   
                }finally{
                    
//                    JOptionPane.showMessageDialog(rootPane, "gagal menghubungkan, periksa ulang koneksi");
//                    loader.setText("");
                }


           }
         };

       thread.start();

    }//GEN-LAST:event_button_simpanActionPerformed

    private void button_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_batalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //you can't see me!
        this.dispose(); //Destroy the JFrame object
        System.exit(0);
    }//GEN-LAST:event_button_batalActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_dbnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dbnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dbnameActionPerformed

    private void txt_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_portActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoneksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoneksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoneksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoneksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoneksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_batal;
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_simpan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldPilihBerkas;
    private javax.swing.JLabel loader;
    private javax.swing.JTextField txt_dbname;
    private javax.swing.JTextField txt_ip;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
