package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CiAddressEmailAddress generated by hbm2java
 */
public class CiAddressEmailAddress  implements java.io.Serializable {


     private BigDecimal ci_addressid;
     private String emailAddress;

    public CiAddressEmailAddress() {
    }

	
    public CiAddressEmailAddress(BigDecimal ci_addressid) {
        this.ci_addressid = ci_addressid;
    }
    public CiAddressEmailAddress(BigDecimal ci_addressid, String emailAddress) {
       this.ci_addressid = ci_addressid;
       this.emailAddress = emailAddress;
    }
   
    public BigDecimal getCi_addressid() {
        return this.ci_addressid;
    }
    
    public void setCi_addressid(BigDecimal ci_addressid) {
        this.ci_addressid = ci_addressid;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }




}


