package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MdMetadataHierarchylv generated by hbm2java
 */
public class MdMetadataHierarchylv  implements java.io.Serializable {

     private BigDecimal mdMetadataid;
     private String hierarchylevel;

    public MdMetadataHierarchylv() {
    }

	
    public MdMetadataHierarchylv(BigDecimal mdMetadataid) {
        this.mdMetadataid = mdMetadataid;
    }
    public MdMetadataHierarchylv(BigDecimal mdMetadataid, String hierarchylevel) {
       this.mdMetadataid = mdMetadataid;
       this.hierarchylevel = hierarchylevel;
    }
   
    public BigDecimal getMdMetadataid() {
        return this.mdMetadataid;
    }
    
    public void setMdMetadataid(BigDecimal mdMetadataid) {
        this.mdMetadataid = mdMetadataid;
    }
    public String getHierarchylevel() {
        return this.hierarchylevel;
    }
    
    public void setHierarchylevel(String hierarchylevel) {
        this.hierarchylevel = hierarchylevel;
    }




}


