# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MenghitungIndexPolygon.py
# Created on: 2018-07-09 17:40:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: MenghitungIndexPolygon <Input_Layer> <Layer_Indeks> <ketersediaan_index2_shp> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

print('Mulai menghitung index')
path_data = "C:\migrasi\\tmp\produksi\\"
path_index = "C:\migrasi\\tmp\ketersediaan_index\\"
path_index_global = "C:\migrasi\ketersediaan_index\\"

# Script arguments
NamaUnsur = arcpy.GetParameterAsText(0)
Input_Layer = path_data + NamaUnsur + ".shp"
if NamaUnsur == '#' or not NamaUnsur:
    Input_Layer = "ADMINISTRASI_AR"  # provide a default value if unspecified
    # Input_Layer = "ADMINISTRASI_AR" # provide a default value if unspecified

SKALA = arcpy.GetParameterAsText(1)
Layer_Indeks = path_index_global + 'INDEKS_' + SKALA + "_REV.shp"
if SKALA == '#' or not SKALA:
    Layer_Indeks = "INDEKS_5K_REV"  # provide a default value if unspecified
    # Layer_Indeks = "INDEKS_5K_REV" # provide a default value if unspecified

ketersediaan_index2_shp = arcpy.GetParameterAsText(2)
if ketersediaan_index2_shp == '#' or not ketersediaan_index2_shp:
    ketersediaan_index2_shp = "C:\\migrasi\\tmp\\ketersediaan_index\\ketersediaan_index.shp"  # provide a default value if unspecified

# Local variables:
ADMINISTRASI_AR_INTERSECT_shp = path_index + NamaUnsur + "_INTERSECT.shp"
ADMINISTRASI_AR_INTERSECT_POINT_shp = path_index + NamaUnsur + "_INTERSECT_POINT.shp"
Layer_Point = ADMINISTRASI_AR_INTERSECT_POINT_shp
Hasil_Selection = Layer_Point


arcpy.MakeFeatureLayer_management(Input_Layer, "input_layer")
arcpy.MakeFeatureLayer_management(Layer_Indeks, "layer_index")

# Process: Intersect
arcpy.Intersect_analysis("input_layer #;layer_index #", ADMINISTRASI_AR_INTERSECT_shp, "ALL", "", "INPUT")

arcpy.MakeFeatureLayer_management(ADMINISTRASI_AR_INTERSECT_shp, "layer_intersect")

# Process: Feature To Point
arcpy.FeatureToPoint_management('layer_intersect', ADMINISTRASI_AR_INTERSECT_POINT_shp, "INSIDE")


arcpy.MakeFeatureLayer_management(ADMINISTRASI_AR_INTERSECT_POINT_shp, "ADMINISTRASI_AR_INTERSECT_POINT_shp")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management('ADMINISTRASI_AR_INTERSECT_POINT_shp', Layer_Point, "", "",
                                  "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;NAMOBJ NAMOBJ VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;")
#
#
arcpy.MakeFeatureLayer_management(Layer_Indeks, "my_Layer_Index")
# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management('my_Layer_Index', "CONTAINS", Layer_Point, "0.05 Meters", "NEW_SELECTION")

# Process: Copy Features
arcpy.CopyFeatures_management('my_Layer_Index', ketersediaan_index2_shp, "", "0", "0", "0")
print "Selsai menghitung index."   