package domain;
// Generated Sep 20, 2017 9:23:56 PM by Hibernate Tools 4.3.1



/**
 * MdScopecode generated by hbm2java
 */
public class MdScopecode  implements java.io.Serializable {


     private String code;
     private String definition;
     private String domainname;

    public MdScopecode() {
    }

	
    public MdScopecode(String code, String domainname) {
        this.code = code;
        this.domainname = domainname;
    }
    public MdScopecode(String code, String definition, String domainname) {
       this.code = code;
       this.definition = definition;
       this.domainname = domainname;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }
    public String getDomainname() {
        return this.domainname;
    }
    
    public void setDomainname(String domainname) {
        this.domainname = domainname;
    }




}


